### ISSUE TITLE
What is the size of alphas?

### ISSUE THREAD

**Issue by ysfalo** [yuantangliang/softmaxfocalloss#2]
I guess the size of alpha should be equal to the number of classes. I wonder whether we can use a single scalar to set the same alpha for all the classes and use
```python
 mx.symbol.SoftmaxFocalOutput(data=self.var_input_data, label=self.var_label,alphas=(0.25),gamma=2) 
```
instead of 
```python
 mx.symbol.SoftmaxFocalOutput(data=self.var_input_data, label=self.var_label,alphas=(0.25, 0.25, 0.25, 0.25),gamma=2) 
```

**Comment by yuantangliang** [comment]
the alpha size should be same as all the classes
