### ISSUE TITLE
Why alpha is a list? How to use it with my own data?

### ISSUE THREAD

**Issue by franciszzj** [yuantangliang/softmaxfocalloss#3]
Why alpha is a list? How to use it with my own data?

In your test code:
`sym = mx.symbol.SoftmaxFocalOutput(data=self.var_input_data, label=self.var_label, alphas=(0.25, 1, 1, 1), gamma=2, use_ignore=True, ignore_label=1,multi_output=True)`

looking forward to your reply

**Comment by yuantangliang** [comment]
each alpha for a class

**Comment by franciszzj** [comment]
Thx! @yuantangliang

**Comment by franciszzj** [comment]
Another problem, when set **multi_output=True**, is it like SoftmaxOutput, do the classification with the channel?

**Comment by yuantangliang** [comment]
yes,the same function as SoftmaxOutput

**Comment by franciszzj** [comment]
Thank you for reply. You did a nice job.
